spring:
  main: #kakaoApiBean
    allow-bean-definition-overriding: true

# 로컬 db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


  # 이미지 업로드 용량
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB




#aws
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USER_NAME}
#    password: ${DATASOURCE_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update #create
#    show-sql: true
#    database: mysql
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#h2
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#    jpa:
#      hibernate:
#        ddl-auto: create
#      show-sql: true
#      database: mysql
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true

# 카카오 API
kakao:
  key: ${KAKAO_KEY}

#AWS-S3 Bucket
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: book-linker-bucket
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2

#인증 에러핸들러 한글 설정
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  file:
    name: error.log # 로그 파일의 경로 및 이름
  level:
    root: INFO # 루트 로거의 로그 레벨
    org.springframework.security: DEBUG # Spring Security 패키지의 로그 레벨
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # 콘솔 출력 로그 패턴
